print("welcoem to Otaku Zone")
print()
user_name = print("hollow " + input('what is your name?\n') )
print()
input("How old are you?\n")
print()
email = input("enter yor emil or phon number\n")
print()
input('what is  your favorite anime?\n')
print()
liek = input('Do you liek manga too?\n')
print()
print("you can now use Otaku Zone")