str_length = input("please type length:\n")
print()
str_width = input("please type width:\n")
print()
meter1 = input("how much for 1 meter?\n")
print()
length = float(str_length)
width = float(str_width)
meter = float(meter1)
area = length*width
total_price = meter*area
str_area = str(area)
str_total_price = str(total_price)
print()
print("the total area is:" + str_area)
print()
print("give the guy:$" +str_total_price)