str_length = input("please type length:\n")
print()
str_width = input("please type width:\n")
print()
length = float(str_length)
width = float(str_width)
area = length*width
str_area = str(area)
print()
print("the total area is:" + str_area)